const experiences = [
  {slug:"djc",period:"2026",index:"01",role:"AI Engineer",company:"Diaspora Junior Consulting",location:"Paris",text:"Système agentique d’aide à la décision sur le marché Forex.",tags:["Python","LangGraph","LLM","FastAPI","Docker","Cloud Run"],metric:"Agentic AI",details:["Analyse technique et génération de signaux","Agent d’analyse fondamentale macroéconomique","Workflow de décision, risque et exécution simulée","Backtesting déterministe vs agentique"]},
  {slug:"datafab",period:"2025",index:"02",role:"Data / ML Engineer",company:"DATAFAB × Kering",location:"Paris",text:"Pipeline ML sur GCP pour le forecasting et la détection d’anomalies e-commerce.",tags:["GCP","Vertex AI","BigQuery","dbt","Airbyte","LSTM"],metric:"ML Platform",details:["Pipelines de collecte et transformation","Forecasting Prophet / LSTM","Automatisation entraînement et prédiction","Orchestration Vertex AI / Cloud Composer"]},
  {slug:"ecam",period:"2024",index:"03",role:"Data Scientist",company:"ECAM",location:"Rennes",text:"Computer Vision pour la reconnaissance de feuilles de parties d’échecs manuscrites.",tags:["Python","OpenCV","ResNet","Deep Learning"],metric:"Computer Vision",details:["Traitement et segmentation d’images","Dataset de plus de 500 images","Fine-tuning d’un ResNet","Pipeline de retranscription automatisée"]}
];

export default function Home(){
 return <main>
  <nav><a className="brand" href="#">ES<span>.</span></a><div className="navlinks"><a href="#experience">Expériences</a><a href="/research">Recherche</a><a href="#about">À propos</a><a className="navCta" href="/cv.pdf" target="_blank">CV ↗</a></div></nav>
  <section className="hero">
   <div className="heroCopy"><div className="eyebrow"><i/> ML / AI ENGINEER <span>· PARIS, FR</span></div><h1>Building AI systems<br/>that <em>move beyond</em><br/>the notebook.</h1><p className="lead">Je conçois des systèmes Machine Learning et GenAI de bout en bout — de l’expérimentation à une architecture robuste, mesurable et déployable.</p><div className="actions"><a className="primary" href="#experience">Voir mes travaux <b>↘</b></a><a className="secondary" href="https://github.com/esanonpro" target="_blank" rel="noreferrer">GitHub ↗</a></div></div>
   <div className="heroVisual"><div className="orbit o1"/><div className="orbit o2"/><div className="core"><span>AI</span><small>SYSTEMS</small></div><div className="node n1">DATA</div><div className="node n2">MODEL</div><div className="node n3">EVAL</div><div className="node n4">SHIP</div></div>
   <div className="heroMeta"><span>01 — RESEARCH</span><span>02 — ENGINEERING</span><span>03 — PRODUCTION</span></div>
  </section>

  <section className="strip"><span className="stripLabel">CURRENT STACK</span>{["Python","LangGraph","GCP","Vertex AI","Docker","FastAPI","TypeScript","Next.js"].map(x=><span key={x}>{x}</span>)}</section>

  <section id="experience" className="section"><header><div><span>01 / SELECTED WORK</span><small>2024 — 2026</small></div><h2>Expériences qui relient<br/><em>modèles et systèmes.</em></h2></header>
   <div className="workList">{experiences.map(e=><a className="work" key={e.slug} href={"/experience/"+e.slug}><div className="workIndex">{e.index}</div><div className="workMain"><div className="workTop"><p>{e.company} · {e.location}</p><span>{e.period}</span></div><h3>{e.role}</h3><p className="workDesc">{e.text}</p><ul>{e.details.map(d=><li key={d}>{d}</li>)}</ul><div className="tags">{e.tags.map(t=><span key={t}>{t}</span>)}</div></div><div className="workSide"><span>{e.metric}</span><b>↗</b></div></a>)}</div>
  </section>

  <section id="research" className="section research"><header><div><span>02 / RESEARCH</span><small>EXPLORE · TEST · MEASURE</small></div><h2>Une pratique d’ingénieur,<br/><em>une démarche de recherche.</em></h2></header>
   <div className="researchGrid"><div className="researchStatement"><span className="mono">RESEARCH DIRECTION</span><p className="bigQuote">Comment rendre les systèmes d’IA plus <em>fiables</em>, évaluables et utiles lorsqu’ils quittent le cadre expérimental ?</p><p>Mes intérêts se situent à l’intersection des systèmes agentiques, des LLM, du Deep Learning et de la décision séquentielle.</p></div><div className="researchTopics">{["Agentic AI","LLM Systems","Reliable ML","Deep Learning","Sequential Decision Making"].map((x,i)=><div key={x}><small>0{i+1}</small><span>{x}</span></div>)}</div></div>
   <div className="researchComing"><span>ACADEMIC WORK / COMING SOON</span><p>Les prochains projets seront documentés comme de vrais travaux de recherche : question, méthode, protocole expérimental, résultats, limites et code reproductible.</p><b>REPOSITORIES →</b></div>
  </section>

  <section id="about" className="section about"><header><div><span>03 / PROFILE</span><small>ENGINEER · BUILDER · RESEARCH-MINDED</small></div><h2>À propos.</h2></header><div className="aboutGrid"><h3>Je transforme une hypothèse en <em>système testable</em>, puis en produit technique.</h3><div><p>Ingénieur Data Science diplômé de l’ENSAI, je travaille sur des problématiques ML/AI où la qualité du modèle ne suffit pas : architecture, reproductibilité, évaluation et déploiement comptent tout autant.</p><p>Mon parcours couvre le Computer Vision, le forecasting, les pipelines ML cloud et les systèmes agentiques.</p><div className="facts"><span><small>EDUCATION</small><b>ENSAI · 2022–2025</b>Diplôme d’ingénieur · Data Science & Ingénierie des données</span><span><small>FOUNDATION</small><b>Université Nazi Boni · 2018–2021</b>Licence Statistiques & Informatique · Bobo-Dioulasso</span><span><small>LANGUAGES</small><b>FR · EN</b>Français natif · English B2</span></div></div></div></section>

  <footer id="contact"><div><span>04 / CONTACT</span><h2>Un problème intéressant<br/>à <em>construire ?</em></h2><p>Disponible pour des opportunités ML / AI Engineering et des collaborations orientées recherche appliquée.</p></div><div className="footerLinks"><a href="mailto:esanon.pro@gmail.com">Email <b>↗</b></a><a href="https://github.com/esanonpro" target="_blank" rel="noreferrer">GitHub <b>↗</b></a></div><small>© 2026 Elie Sanon <span>Next.js · TypeScript · Vercel</span></small></footer>
 </main>
}