const experiences = [
  {slug:"djc",period:"2026",index:"01",role:"AI Engineer",company:"Diaspora Junior Consulting",location:"Paris",text:"Système agentique d’aide à la décision sur le marché Forex.",tags:["Python","LangGraph","LLM","FastAPI","Docker","Cloud Run"],metric:"Agentic AI",details:["Analyse technique et génération de signaux","Agent d’analyse fondamentale macroéconomique","Workflow de décision, risque et exécution simulée","Backtesting déterministe vs agentique"]},
  {slug:"datafab",period:"2025",index:"02",role:"Data / ML Engineer",company:"DATAFAB × Kering",location:"Paris",text:"Pipeline ML sur GCP pour le forecasting et la détection d’anomalies e-commerce.",tags:["GCP","Vertex AI","BigQuery","dbt","Airbyte","LSTM"],metric:"ML Platform",details:["Pipelines de collecte et transformation","Forecasting Prophet / LSTM","Automatisation entraînement et prédiction","Orchestration Vertex AI / Cloud Composer"]},
  {slug:"ecam",period:"2024",index:"03",role:"Data Scientist",company:"ECAM",location:"Rennes",text:"Computer Vision pour la reconnaissance de feuilles de parties d’échecs manuscrites.",tags:["Python","OpenCV","ResNet","Deep Learning"],metric:"Computer Vision",details:["Traitement et segmentation d’images","Dataset de plus de 500 images","Fine-tuning d’un ResNet","Pipeline de retranscription automatisée"]}
];

export default function Home(){
 return <main>
  <nav><a className="brand" href="#">ES<span>.</span></a><div className="navlinks"><a href="#experience">Expériences</a><a href="/research">Recherche</a><a href="#about">À propos</a><a className="navCta" href="/cv_elie_sanon.pdf" target="_blank" rel="noreferrer">CV ↗</a></div></nav>
  <section className="hero heroV21">
   <div className="heroCopy"><div className="eyebrow"><i/> ELIE SANON <span>· PARIS, FR</span></div><h1>ML / AI Engineer.<br/><em>Research to production.</em></h1><p className="lead">Je conçois des systèmes Machine Learning et GenAI de bout en bout — de l’expérimentation à une architecture robuste, mesurable et déployable.</p><div className="actions"><a className="primary" href="#experience">Voir mes travaux <b>↘</b></a><a className="secondary" href="https://github.com/esanonpro" target="_blank" rel="noreferrer">GitHub ↗</a></div></div>
   <div className="heroVisual heroVisualV3" aria-label="AI systems lifecycle"><div className="orbit o1"/><div className="orbit o2"/><div className="core"><span>AI</span><small>SYSTEMS</small></div><div className="node n1">DATA</div><div className="node n2">MODEL</div><div className="node n3">EVAL</div><div className="node n4">SHIP</div><div className="visualCaption">RESEARCH → SYSTEMS → PRODUCTION</div></div>
  </section>

  <section className="strip"><span className="stripLabel">CURRENT STACK</span>{["Python","LangGraph","GCP","Vertex AI","Docker","FastAPI","TypeScript","Next.js"].map(x=><span key={x}>{x}</span>)}</section>

  <section id="experience" className="section"><header><div><span>01 / SELECTED WORK</span><small>2024 — 2026</small></div><h2>Expériences qui relient<br/><em>modèles et systèmes.</em></h2></header>
   <div className="workList">{experiences.map(e=><a className="work" key={e.slug} href={"/experience/"+e.slug}><div className="workIndex">{e.index}</div><div className="workMain"><div className="workTop"><p>{e.company} · {e.location}</p><span>{e.period}</span></div><h3>{e.role}</h3><p className="workDesc">{e.text}</p><ul>{e.details.map(d=><li key={d}>{d}</li>)}</ul><div className="tags">{e.tags.map(t=><span key={t}>{t}</span>)}</div></div><div className="workSide"><span>{e.metric}</span><b>↗</b></div></a>)}</div>
  </section>

  <section id="research" className="section research"><header><div><span>02 / RESEARCH</span><small>EXPLORE · TEST · MEASURE</small></div><h2>Une pratique d’ingénieur,<br/><em>une démarche de recherche.</em></h2></header>
   <div className="researchGrid"><div className="researchStatement"><span className="mono">RESEARCH DIRECTION</span><p className="bigQuote">Comment rendre les systèmes d’IA plus <em>fiables</em>, évaluables et utiles lorsqu’ils quittent le cadre expérimental ?</p><p>Mes travaux académiques explorent le Deep Learning, le Computer Vision, les séries temporelles et l’efficacité statistique ; mes expériences récentes étendent cette démarche aux systèmes agentiques et aux LLM.</p></div><div className="researchTopics">{["Deep Learning","Computer Vision","Time Series","Efficient ML","Agentic AI"].map((x,i)=><div key={x}><small>0{i+1}</small><span>{x}</span></div>)}</div></div>
   <div className="researchComing"><span>SELECTED ACADEMIC WORK</span><p>Deux travaux ENSAI documentés : débruitage d’images par Transformers et calibration rapide de modèles GARCH, avec méthodes, protocoles, résultats et limites.</p><a href="/research"><b>EXPLORER LES TRAVAUX ↗</b></a></div>
   <div className="homeResearchWorks"><a href="/research/image-denoising-transformers"><small>01 · DEEP LEARNING / COMPUTER VISION</small><h3>Weakly-Supervised Image Denoising with Transformers</h3><p>SCUNet2 · Swin Transformer · Noise2VST · Self-Supervised Learning</p><b>Voir l’étude ↗</b></a><a href="/research/fast-garch-calibration"><small>02 · COMPUTATIONAL STATISTICS / TIME SERIES</small><h3>Fast Calibration of GARCH Models</h3><p>One-step estimator · Monte Carlo · GARCH · S&P 500</p><b>Voir l’étude ↗</b></a></div>
  </section>

  <section id="about" className="section about"><header><div><span>03 / PROFILE</span><small>ENGINEER · BUILDER · RESEARCH-MINDED</small></div><h2>À propos.</h2></header><div className="aboutGrid"><h3>Je transforme une hypothèse en <em>système testable</em>, puis en produit technique.</h3><div><p>Ingénieur Data Science diplômé de l’ENSAI, je travaille sur des problématiques ML/AI où la qualité du modèle ne suffit pas : architecture, reproductibilité, évaluation et déploiement comptent tout autant.</p><p>Mon parcours couvre le Computer Vision, le forecasting, les pipelines ML cloud et les systèmes agentiques.</p><div className="facts"><span><small>EDUCATION</small><b>ENSAI · 2022–2025</b>Diplôme d’ingénieur · Data Science & Ingénierie des données</span><span><small>FOUNDATION</small><b>Université Nazi Boni · 2018–2021</b>Licence Statistiques & Informatique · Bobo-Dioulasso</span><span><small>LANGUAGES</small><b>FR · EN</b>Français natif · English B2</span></div></div></div></section>

  <section id="education" className="section education"><header><div><span>04 / EDUCATION</span><small>STATISTICS · COMPUTER SCIENCE · DATA ENGINEERING</small></div><h2>Formation scientifique,<br/><em>orientation ingénierie.</em></h2></header><div className="educationList"><article><div className="eduDate">2022 — 2025</div><div><span>ENSAI · Rennes</span><h3>Diplôme d’ingénieur</h3><p>Spécialisation <b>Data Science & Ingénierie des données</b>. Cursus combinant statistique, mathématiques, informatique et méthodes quantitatives, puis spécialisation orientée Big Data, architecture des systèmes et traitement de grands volumes de données.</p><div className="tags"><span>Data Science</span><span>Machine Learning</span><span>Big Data</span><span>Data Engineering</span></div></div></article><article><div className="eduDate">2018 — 2021</div><div><span>Université Nazi Boni · Bobo-Dioulasso, Burkina Faso</span><h3>Licence Statistiques & Informatique</h3><p>Socle académique en statistique et informatique, à l’origine de mon parcours en science des données et ingénierie ML.</p><div className="tags"><span>Statistiques</span><span>Informatique</span></div></div></article></div></section>

  <footer id="contact"><div><span>05 / CONTACT</span><h2>Un problème intéressant<br/>à <em>construire ?</em></h2><p>Disponible pour des opportunités ML / AI Engineering et des collaborations orientées recherche appliquée.</p></div><div className="footerLinks"><a href="mailto:eliegislainsanon@gmail.com">Email <b>↗</b></a><a href="https://github.com/esanonpro" target="_blank" rel="noreferrer">GitHub <b>↗</b></a></div><small>© 2026 Elie Sanon <span>Next.js · TypeScript · Vercel</span></small></footer>
 </main>
}