import Header from "../components/Header";
import {Card,Chip,SectionHeader} from "../components/ui";
import {experiences,projects,site,skills} from "../content/site";

export default function Home(){
 return <><Header/><main id="main">
  <section className="hero heroRefactor" aria-labelledby="hero-title"><div className="heroCopy"><div className="eyebrow"><i/> {site.name} <span className="availability">● {site.availability}</span></div><h1 id="hero-title">{site.role}.<br/><em>Research to production.</em></h1><p className="lead">{site.value}</p><p className="proof">{site.proof}</p><div className="actions"><a className="primary" href="#experience">Voir mes travaux ↓</a><a className="secondary" href={site.github} target="_blank" rel="noreferrer">GitHub ↗</a></div></div><div className="pipelineHero" aria-label="Cycle de développement : données, modèle, évaluation, déploiement"><span>DATA</span><i>→</i><span>MODEL</span><i>→</i><span>EVAL</span><i>→</i><span>SHIP</span></div></section>
  <section className="stackStrip" aria-label="Stack principale">{["Python","PyTorch","LangGraph","GCP","Docker","FastAPI","SQL"].map(x=><span key={x}>{x}</span>)}</section>

  <section id="experience" className="section"><SectionHeader index="01" kicker="EXPÉRIENCES" title="Ce que j’ai conçu et livré."/><div className="workList">{experiences.map((e,i)=><a className="work" key={e.slug} href={"/experience/"+e.slug}><div className="workIndex">{String(i+1).padStart(2,"0")}</div><div className="workMain"><div className="workTop"><p>{e.company} · {e.location}</p><span>{e.period}</span></div><h3>{e.role}</h3><p className="workDesc">{e.context}</p><ul>{e.actions.map(a=><li key={a}>{a}</li>)}</ul><p className="resultLine"><b>Résultat :</b> {e.result}</p><div className="tags">{e.stack.map(t=><Chip key={t}>{t}</Chip>)}</div></div><div className="workSide"><span>{e.category}</span><b>↗</b></div></a>)}</div></section>

  <section id="projects" className="section"><SectionHeader index="02" kicker="ENGINEERING PROJECTS" title="Du prototype au système exploitable."/><div className="projectGrid">{projects.map(p=><Card key={p.slug} href={p.githubUrl} eyebrow={p.eyebrow} title={p.title} external><p>{p.problem}</p><div className="miniFlow">{p.architecture.slice(0,5).map((x,i)=><span key={x}>{x}{i<4&&<i>→</i>}</span>)}</div><p className="cardMetric"><strong>Évaluation</strong> {p.metrics}</p></Card>)}</div></section>

  <section id="research" className="section"><SectionHeader index="03" kicker="RECHERCHE APPLIQUÉE" title="Hypothèses, protocoles, résultats, limites."/><div className="projectGrid"><Card href="/research/image-denoising-transformers" eyebrow="DEEP LEARNING · COMPUTER VISION" title="Weakly-Supervised Image Denoising"><p>SCUNet2 atteint 29,27 dB avec GAT sur Set12, contre 29,25 dB pour DRUNet : un écart faible, sans conclusion de supériorité générale.</p></Card><Card href="/research/fast-garch-calibration" eyebrow="STATISTICAL LEARNING · TIME SERIES" title="Fast Calibration of GARCH Models"><p>À n=70k, l’estimateur one-step réduit fortement le temps de calcul observé par rapport au QML, selon le réglage étudié.</p></Card></div><a className="sectionLink" href="/research">Explorer les études et leurs visuels →</a></section>

  <section id="skills" className="section"><SectionHeader index="04" kicker="COMPÉTENCES" title="Une stack organisée par usage."/><div className="skillsGrid">{skills.map(g=><article key={g.group}><h3>{g.group}</h3><div className="tags">{g.items.map(x=><Chip key={x}>{x}</Chip>)}</div></article>)}</div></section>

  <section id="about" className="section about"><SectionHeader index="05" kicker="PROFIL" title="Ingénieur, avec une démarche de recherche."/><div className="aboutGrid"><h3>Transformer une hypothèse en <em>système testable</em>, puis en produit technique.</h3><p>Ingénieur Data Science diplômé de l’ENSAI, je travaille à l’intersection du Machine Learning, de l’ingénierie des données et des systèmes GenAI. Je privilégie les protocoles mesurables, la reproductibilité et le déploiement plutôt que les démonstrations isolées.</p></div></section>
 </main><footer id="contact"><div><span>06 / CONTACT</span><h2>Échangeons sur un problème<br/><em>à construire.</em></h2><p>{site.availability}. Contact direct par email, LinkedIn ou GitHub.</p></div><div className="footerLinks"><a href={"mailto:"+site.email}>Email <b>↗</b></a><a href={site.linkedin} target="_blank" rel="noreferrer">LinkedIn <b>↗</b></a><a href={site.github} target="_blank" rel="noreferrer">GitHub <b>↗</b></a></div><small>© 2026 Elie Sanon <span>Next.js · TypeScript · Vercel</span></small></footer></>
}